### ISSUE TITLE
Deleting the vehicle with radio playing does not stop radio and results into radio playing from everywhere

### ISSUE THREAD

**Issue by brezerk** [BrettMayson/ArmaRadio#7]
Hi.

Thanks for a great mod.

We found an issue with radio playing after vehicle deletion.

Steps to reproduce:
1. Spawn vehicle
2. Turn on radio;
3. Delete vehicle with `deleteVehicle cursorTarget`;

Issue:
1. Radio is playing from everywhere still with no option to stop this :)

Expected behavior:
1. Radio is stop playing;

**Comment by BrettMayson** [comment]
Fixed in 0.6, pending release to the Steam Workshop
