### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by brezerk** [BrettMayson/ArmaRadio#8]
Playing online radio seems to be causing High CPU usage.
+ CPU consumption remains the same even if you far away from radio source. 

Steps to reproduce: 
1. Place radio object.
2. Start mission.
3. Check current CPU usage;
4. Use ACE menu, select radio, turn it on;
5. Check current CPU usage;
6. Teleport or travel far away;
7. Check current CPU usage;
8. Get back, turn off radio;
9. Check current CPU usage;

**Comment by BrettMayson** [comment]
The internet radio will still be streamed regardless of distance to the source, there are no plans to change how it works at the moment.

**Comment by BrettMayson** [comment]
Updated for 0.8.0

The radio will still be streamed regardless of distance, but improvements have been made when multiple radios are playing the same station, and the internals have been capped to 60 fps reduce CPU usage
